services:
  server-auth:
    container_name: server-auth
    build:
      context: ./serverAuth
      dockerfile: Dockerfile
    networks:
      - application-net
    ports:
      - 8080:8080
  
  main-backend:
    container_name: main-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - 5000:5000
    networks:
      - application-net
    depends_on:
      - server-auth

  app-frontend:
    container_name: app-frontend
    build: 
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    environment:
      - NODE_ENV=production
    ports:
      - 3000:5173
    networks:
      - application-net
    depends_on:
      - main-backend

  
networks:
  application-net: 
    driver: bridge

